[2025-01-31T04:45:36.503+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_v2.second_task scheduled__2022-04-13T00:00:00+00:00 [queued]>
[2025-01-31T04:45:36.519+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_v2.second_task scheduled__2022-04-13T00:00:00+00:00 [queued]>
[2025-01-31T04:45:36.519+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-01-31T04:45:36.547+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): second_task> on 2022-04-13 00:00:00+00:00
[2025-01-31T04:45:36.557+0000] {standard_task_runner.py:57} INFO - Started process 3511 to run task
[2025-01-31T04:45:36.562+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag1_v2', 'second_task', 'scheduled__2022-04-13T00:00:00+00:00', '--job-id', '920', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmpwroqhvmo']
[2025-01-31T04:45:36.565+0000] {standard_task_runner.py:85} INFO - Job 920: Subtask second_task
[2025-01-31T04:45:36.703+0000] {task_command.py:415} INFO - Running <TaskInstance: dag1_v2.second_task scheduled__2022-04-13T00:00:00+00:00 [running]> on host f8bdfcb8bca5
[2025-01-31T04:45:36.912+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='anhtupham99' AIRFLOW_CTX_DAG_ID='dag1_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2022-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-04-13T00:00:00+00:00'
[2025-01-31T04:45:36.914+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-31T04:45:36.915+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo I am the second task, I run after the first task']
[2025-01-31T04:45:36.936+0000] {subprocess.py:86} INFO - Output:
[2025-01-31T04:45:36.939+0000] {subprocess.py:93} INFO - I am the second task, I run after the first task
[2025-01-31T04:45:36.940+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-31T04:45:36.989+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1_v2, task_id=second_task, execution_date=20220413T000000, start_date=20250131T044536, end_date=20250131T044536
[2025-01-31T04:45:37.062+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-31T04:45:37.098+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
