[2025-01-31T04:45:10.702+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_v2.second_task scheduled__2022-03-03T00:00:00+00:00 [queued]>
[2025-01-31T04:45:10.713+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_v2.second_task scheduled__2022-03-03T00:00:00+00:00 [queued]>
[2025-01-31T04:45:10.714+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-01-31T04:45:10.729+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): second_task> on 2022-03-03 00:00:00+00:00
[2025-01-31T04:45:10.736+0000] {standard_task_runner.py:57} INFO - Started process 3240 to run task
[2025-01-31T04:45:10.740+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag1_v2', 'second_task', 'scheduled__2022-03-03T00:00:00+00:00', '--job-id', '833', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmpf9gj7fis']
[2025-01-31T04:45:10.741+0000] {standard_task_runner.py:85} INFO - Job 833: Subtask second_task
[2025-01-31T04:45:10.821+0000] {task_command.py:415} INFO - Running <TaskInstance: dag1_v2.second_task scheduled__2022-03-03T00:00:00+00:00 [running]> on host f8bdfcb8bca5
[2025-01-31T04:45:10.931+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='anhtupham99' AIRFLOW_CTX_DAG_ID='dag1_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2022-03-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-03-03T00:00:00+00:00'
[2025-01-31T04:45:10.933+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-31T04:45:10.934+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo I am the second task, I run after the first task']
[2025-01-31T04:45:10.945+0000] {subprocess.py:86} INFO - Output:
[2025-01-31T04:45:10.947+0000] {subprocess.py:93} INFO - I am the second task, I run after the first task
[2025-01-31T04:45:10.947+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-31T04:45:10.973+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1_v2, task_id=second_task, execution_date=20220303T000000, start_date=20250131T044510, end_date=20250131T044510
[2025-01-31T04:45:10.995+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-31T04:45:11.012+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
